### ISSUE TITLE
Usage of Dioxus components

### ISSUE THREAD

**Issue by marc2332** [albbus-stack/t5.rs#1]
hey! Very interesting project, I hope you continue with it.

I see you are currently separating the UI in a sort type of Components but not exactly, it should be improved :D

You are currently doing it like this:

```rs
fn app() -> Element {
   rsx!(
       button { "hey" }
       {whatever(123)}
   )
}

fn whatever(value: usize) -> Element {
   rsx!(
       p { "whatever -> {value}" }
   )
}
```

But it should be like this:

```rs
fn app() -> Element {
   rsx!(
       button { "hey" }
       Whatever {
          value: 123
       }
   )
}

#[component]
fn Whatever(value: usize) -> Element {
   rsx!(
       p { "whatever -> {value}" }
   )
}
```

:v: 😄

**Comment by marc2332** [comment]
Otherwise, the whole app will run as a one single component, which will eventually lead to issues as hooks cannot be called conditionally, or performance problems

**Comment by albbus-stack** [comment]
@marc2332 Thank you for the heads up, I'm going to refactor it asap 🤘

**Comment by albbus-stack** [comment]
@marc2332 I'll happily wait if you want to review the code in #2, tested it and it works!
